#!/bin/bash

#install linux system dependencies
apt-get update
apt-get install python3
apt-get install python3-pip
apt-get install redis-server
apt-get install can-utils
apt-get install i2c-tools
apt-get install python-smbus
sudo apt-get install python-rpi.gpio
apt install python3-tk
apt install postgresql libpq-dev postgresql-client postgresql-client-common -y
# apt-get install python-usb python3-usb
apt-get install libusb-1.0-0 libusb-1.0-0-dev
apt-get install libudev-dev libfox-1.6-dev autotools-dev autoconf automake libtool

# install python dependencies
pip3 install python-can
pip3 install redis
pip3 install blessed
pip3 install psycopg2-binary
pip3 install pyyaml
pip3 install smbus
pip install pyyaml #not sure why we need this, but we do
pip3 install canopen
# pip3 install pyusb #pretty sure we can remove this

#compiling USB driver C library dependencies
cd drivers/usb_dependencies
cp 61-mcc.rules /etc/udev/rules.d/99-mcc.rules

cd hidapi
chmod +x bootstrap
./bootstrap
./configure
make
make install

cd ../mcc-libusb
make
make install
ldconfig



cd ../../..  #go up 3 levels from SCADA_2021/drivers/usb_dependencies/mcc-libusb/ to SCADA_2021/

#Creating GUI Startup Files 

# copy lxsession file into the .config folder
#cd /usr/etc/scada/GUI 
sudo chmod +x GUI/MainGUI.py 
#sudo chmod +x /usr/etc/scada/GUI

cd /usr/bin
sudo chmod +x scada_gui.py #NOTE TO TEAM: this doesn't work unless you've already run make
cp -r /etc/xdg/lxsession /home/pi/.config
cd /home/pi/.config/lxsession/LXDE-pi
## ADD the following line to the end of the file 
echo '@/usr/bin/scada_gui.py' >> autostart
##Restart pi 

# Creating Bit-Banged I2C BUS to support clock strecthing for BNO-055 IMU 
cd /boot 
echo 'dtoverlay=i2c-gpio,bus=3,i2c_gpio_sda=02,i2c_gpio_scl=03' >> config.txt

# Adding the RTC setup file to rclocal for rtc setup on boot
cd /etc
echo 'sudo python3 /usr/bin/scadartc_setup.py' >> rc.local

# Setup Can 
cd /boot
echo 'dtparam=spi=on' >> config.txt
echo 'dtoverlay=mcp2515-can0,oscillator=16000000,interrupt=25' >> config.txt 
echo 'dtoverlay=spi-bcm2835-overlay' >> config.txt 

echo 'INSTALL COMPLETE'