Sensors:
  Cool Fan:
    cal_function: ''
    data_type: velocity
    input_targets: ''
    oprange: []
    output_target: cool:fan
    subsystem: Cooling
    unit: RPM
  Cool Flow Rate:
    cal_function: ''
    data_type: flowRate
    input_targets: ''
    oprange: []
    output_target: cool:flowRate
    subsystem: Cooling
    unit: ''
  Cool Pump:
    cal_function: ''
    data_type: pump
    input_targets: ''
    oprange: []
    output_target: cool:pump
    subsystem: Cooling
    unit: ''
  Cool Temp1:
    cal_function: ''
    data_type: temp
    input_targets: ''
    oprange: []
    output_target: cool:temp
    subsystem: Cooling
    unit: C
  Cool Temp2:
    cal_function: ''
    data_type: temp
    input_targets: ''
    oprange: []
    output_target: cool:temp2
    subsystem: Cooling
    unit: ''
  GLV_Current:
    cal_function: x0
    data_type: current
    input_targets:
    - glv:current:raw
    oprange:
    - 10
    - 15
    - 65
    - 70
    output_target: glv:current
    subsystem: GLV
    unit: A
  GLV_Power:
    cal_function: x0*x1
    data_type: power
    input_targets:
    - glv:current
    - glv:voltage
    oprange:
    - 10
    - 15
    - 65
    - 70
    output_target: glv:power
    subsystem: GLV
    unit: W
  GLV_Temp:
    cal_function: x0
    data_type: temp
    input_targets:
    - glv:temp:raw
    oprange:
    - 10
    - 15
    - 65
    - 70
    output_target: glv:temp
    subsystem: GLV
    unit: C
  GLV_Voltage:
    cal_function: x0
    data_type: voltage
    input_targets:
    - glv:voltage:raw
    oprange:
    - 10
    - 15
    - 65
    - 70
    output_target: glv:voltage
    subsystem: GLV
    unit: V
  Motor Aux:
    cal_function: x0
    data_type: state
    input_targets:
    - motor-3:aux
    oprange: []
    output_target: motor:aux
    subsystem: Motor
    unit: ''
  Motor Brake:
    cal_function: x0
    data_type: state
    input_targets:
    - motor-3:brake
    oprange: []
    output_target: motor:brake
    subsystem: Motor
    unit: ''
  Motor Controller Temp:
    cal_function: x0
    data_type: temp
    input_targets:
    - motor-2:controller_temp
    oprange: []
    output_target: motor:controller_temp
    subsystem: Motor
    unit: ''
  Motor Current Demand:
    cal_function: x0
    data_type: state
    input_targets:
    - motor-2:current_demand
    oprange: []
    output_target: motor:current_demand
    subsystem: Motor
    unit: ''
  Motor Flux Regulator:
    cal_function: x0
    data_type: state
    input_targets:
    - motor-4:flux_regulator
    oprange: []
    output_target: motor:flux_regulator
    subsystem: Motor
    unit: ''
  Motor Phaseb Current:
    cal_function: x0
    data_type: state
    input_targets:
    - motor-3:phaseb_current
    oprange: []
    output_target: motor:brake
    subsystem: Motor
    unit: ''
  Motor RPM:
    cal_function: x0
    data_type: velocity
    input_targets:
    - motor-4:velocity
    oprange: []
    output_target: motor:velocity
    subsystem: Motor
    unit: RPM
  Motor Status:
    cal_function: x0
    data_type: state
    input_targets:
    - motor:status
    oprange: []
    output_target: motor:status
    subsystem: Motor
    unit: ''
  Motor Temp:
    cal_function: x0
    data_type: temp
    input_targets:
    - motor-2:motor_temp
    oprange: []
    output_target: motor:motor_temp
    subsystem: Motor
    unit: C
  Motor Throttle:
    cal_function: x0 * x1 * 256
    data_type: voltage
    input_targets:
    - motor:throttle-byte0
    - motor:throttle-byte1
    oprange: []
    output_target: scada:throttle
    subsystem: Motor
    unit: mV
  Motor Torque:
    cal_function: x0
    data_type: state
    input_targets:
    - motor:torque
    oprange: []
    output_target: motor:torque
    subsystem: Motor
    unit: ''
  Motor Torque Regulator:
    cal_function: x0
    data_type: state
    input_targets:
    - motor-4:torque_regulator
    oprange: []
    output_target: motor:torque_regulator
    subsystem: Motor
    unit: ''
  Motor Velocity:
    cal_function: x0
    data_type: velocity
    input_targets:
    - motor-4:velocity
    oprange: []
    output_target: motor:velocity
    subsystem: Motor
    unit: m/s^2
  Motor Voltage:
    cal_function: x0
    data_type: voltage
    input_targets:
    - motor-2:dc_link_voltage
    oprange: []
    output_target: motor:dc_link_voltage
    subsystem: Motor
    unit: V
  Motor Warning:
    cal_function: x0
    data_type: state
    input_targets:
    - motor-2:warning
    oprange: []
    output_target: motor:warning
    subsystem: Motor
    unit: ''
  Pack 1 Ambient Temp:
    cal_function: (x0 * (9/5) +32)
    data_type: temp
    input_targets:
    - PACK1:cells:temp:min
    - PACK1:cells:temp:avg
    - PACK1:cells:temp:max
    oprange:
    - null
    - null
    - 250
    - 300
    output_target: 'PACK1: AMBIENT_TEMP'
    subsystem: Pack1
    unit: C
  Pack 1 Current:
    cal_function: x0
    data_type: current
    input_targets:
    - PACK1:current
    oprange:
    - null
    - null
    - 250
    - 300
    output_target: 'PACK1: CURRENT'
    subsystem: Pack1
    unit: A
  Pack 1 SOC:
    cal_function: x0, x1
    data_type: SOC
    input_targets:
    - PACK1:state_of_charge_01
    - PACK1:state_of_charge_02
    oprange:
    - 10
    - 20
    - 100
    - 105
    output_target: 'PACK1: SOC_1'
    subsystem: Pack1
    unit: '%'
  Pack 1 Voltage:
    cal_function: x0
    data_type: voltage
    input_targets:
    - PACK1:voltage
    oprange:
    - null
    - null
    - 250
    - 300
    output_target: 'PACK1: VOLTAGE'
    subsystem: Pack1
    unit: V
  Pack 2 Ambient Temp:
    cal_function: (x0 * (9/5) +32)
    data_type: temp
    input_targets:
    - PACK2:cells:temp:min
    - PACK2:cells:temp:avg
    - PACK2:cells:temp:max
    oprange:
    - null
    - null
    - 250
    - 300
    output_target: 'PACK2: AMBIENT_TEMP'
    subsystem: Pack2
    unit: C
  Pack 2 Current:
    cal_function: x0
    data_type: current
    input_targets:
    - PACK2:current
    oprange:
    - null
    - null
    - 250
    - 300
    output_target: 'PACK2: CURRENT'
    subsystem: Pack2
    unit: A
  Pack 2 SOC:
    cal_function: x0, x1
    data_type: SOC
    input_targets:
    - PACK2:state_of_charge_01
    - PACK2:state_of_charge_02
    oprange:
    - 10
    - 20
    - 100
    - 105
    output_target: 'PACK2: SOC_1'
    subsystem: Pack2
    unit: '%'
  Pack 2 Voltage:
    cal_function: x0
    data_type: voltage
    input_targets:
    - PACK2:voltage
    oprange:
    - null
    - null
    - 250
    - 300
    output_target: 'PACK2: VOLTAGE'
    subsystem: Pack2
    unit: V
  TSI Current:
    cal_function: x0
    data_type: current
    input_targets:
    - tsi:current:raw
    oprange:
    - null
    - null
    - 250
    - 300
    output_target: tsi:current
    subsystem: TSI
    unit: A
  TSI Flow Rate:
    cal_function: 0.0535 + 757.5 * (1/x0)
    data_type: flowRate
    input_targets:
    - tsi:flow_rate:raw
    oprange: []
    output_target: tsi:flow_rate
    subsystem: TSI
    unit: ''
  TSI TS Voltage:
    cal_function: (((x0/255) * 5) -1.28) *61
    data_type: voltage
    input_target: ('tsi:voltage:raw',)
    output_target: tsi:Voltage
    subsystem: TSI
    unit: V
  TSI Throttle:
    cal_function: (((x0 / 255) * 3.3)*33)/18
    data_type: voltage
    input_targets:
    - tsi:throttle:raw
    oprange: []
    output_target: tsi:throttle
    subsystem: TSI
    unit: ''
  TSI_Drive_State:
    cal_function: x0
    data_type: state
    input_targets:
    - tsi:state:int
    oprange:
    - 80
    - 90
    - 120
    - 150
    output_target: tsi:state
    subsystem: TSI
    unit: ''
  TSI_MC_Voltage:
    cal_function: (((x0/255) * 5) -1.28) *61
    data_type: voltage
    input_targets:
    - tsi:mc_voltage:raw
    oprange: []
    output_target: tsi:mc_voltage
    subsystem: TSI
    unit: V
Sort_Data:
  data_type: null
  subsystem: null
bus_info:
  bitrate: 125000
  bustype: socketcan
  channel: vcan0
can_nodes:
  1: MOTOR
  3: TSI
  4: PACK1
  5: PACK2
dont_log:
- '*:raw'
- motor:*
- emulator:*
emulate_cockpit: false
emulate_motorcontroller: false
emulate_nodes: true
emulate_packs: false
emulate_tsi: false
process_data:
  MOTOR:
  - status
  - dummy2
  - torque
  - dummy4
  - dummy5
  - dummy6
  - dummy7
  - dummy9
  MOTOR-2:
  - motor_temp
  - controller_temp
  - dc_link_voltage
  - warning
  - current_demand
  - test
  MOTOR-3:
  - throttle-byte0
  - throttle-byte1
  - aux
  - brake
  - phaseb_current
  - dummy5
  - dummy6
  - dummy7
  MOTOR-4:
  - torque_regulator
  - flux_regulator
  - velocity
  PACK1:
  - voltage
  - current
  - state_of_charge_01
  - state_of_charge_02
  - temp
  - cells:temp:min
  - cells:temp:avg
  - cells:temp:max
  PACK2:
  - voltage
  - current
  - state_of_charge_01
  - state_of_charge_02
  - temp
  - cells:temp:min
  - cells:temp:avg
  - cells:temp:max
  TSI:
  - conditions
  - mc_voltage:raw
  - voltage:raw
  - cooling_temp:raw
  - throttle:raw
  - flow_rate:raw
  - state:int
  - current:raw
sensor_metadata:
  tsi:throttle:
    oprange:
    - 0
    - 0
    - 5
    - 5
    unit: V
